name: SUKUTTYO-BBS Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'ユーザー名 (ゲストの場合は「O」)'
        required: true
        default: 'O'
      message:
        description: 'メッセージ (オプション)'
        required: false

# 書き込み権限を追加
permissions:
  contents: write

jobs:
  sukuttyo_bbs_chat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # 全ての履歴を取得
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Create SUKUTTYO BBS Chat Script
        env:
          USERNAME: ${{ github.event.inputs.username }}
          INITIAL_MESSAGE: ${{ github.event.inputs.message }}
        run: |
          cat > sukuttyo_bbs_chat.py << EOL
          import os
          import sys
          import time
          import threading
          import uuid

          class SukuttyoBBS:
              def __init__(self, username):
                  self.username = username if username else 'O'
                  self.session_id = str(uuid.uuid4())
                  self.readme_file = 'README.md'
                  self.running = True

              def send_message(self, message):
                  """メッセージをREADMEに送信"""
                  try:
                      # READMEの現在の内容を読み込み
                      try:
                          with open(self.readme_file, 'r', encoding='utf-8') as f:
                              existing_content = f.read()
                      except FileNotFoundError:
                          existing_content = "# SUKUTTYO@BBS チャットログ\n\n"

                      # 新しいメッセージを追加
                      log_message = f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] {self.username}> {message}\n\n"
                      
                      # READMEを更新
                      with open(self.readme_file, 'w', encoding='utf-8') as f:
                          f.write(existing_content + log_message)
                      
                      # 標準出力に直接表示
                      print(log_message.strip(), flush=True)
                  except Exception as e:
                      print(f"メッセージ送信エラー: {e}", flush=True)

              def start_chat(self, initial_message=None):
                  """チャットセッションの開始"""
                  # 開始メッセージ
                  self.send_message("SUKUTTYOセッションを開始します")
                  
                  # 初期メッセージがある場合は送信
                  if initial_message:
                      self.send_message(initial_message)

                  # 6時間の制限
                  start_time = time.time()
                  max_duration = 6 * 60 * 60  # 6時間

                  print(f"SUKUTTYO@BBS - {self.username}としてログイン", flush=True)
                  print("メッセージを入力 (exitで終了)", flush=True)

                  while time.time() - start_time < max_duration:
                      try:
                          # 標準入力から読み取り
                          message = input(f"{self.username}> ")
                          
                          if message.lower() in ['exit', 'quit']:
                              self.send_message("セッションを終了します")
                              break
                          
                          if message:
                              self.send_message(message)
                      
                      except EOFError:
                          # GitHub Actionsでの入力制限に対応
                          break
                      except KeyboardInterrupt:
                          break

                  # 終了処理
                  self.send_message("セッションを終了します")
                  self.running = False

          def main():
              username = os.environ.get('USERNAME', 'O')
              initial_message = os.environ.get('INITIAL_MESSAGE', None)
              
              bbs = SukuttyoBBS(username)
              bbs.start_chat(initial_message)

          if __name__ == "__main__":
              main()
          EOL

      - name: Create README if not exists
        run: |
          if [ ! -f README.md ]; then
            echo "# SUKUTTYO@BBS チャットログ" > README.md
          fi

      - name: Commit and Push README
        env:
          # GitHubトークンを使用
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 全てのファイルを追加
          git add .
          
          # コミットとプッシュ
          git commit -m "Update SUKUTTYO BBS chat log" || echo "No changes to commit"
          git push

      - name: Run SUKUTTYO BBS
        env:
          USERNAME: ${{ github.event.inputs.username }}
          INITIAL_MESSAGE: ${{ github.event.inputs.message }}
        run: |
          python sukuttyo_bbs_chat.py
