name: SUKUTTYO-BBS Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'ユーザー名 (ゲストの場合は「O」)'
        required: true
        default: 'O'
      message:
        description: 'メッセージ (オプション)'
        required: false

permissions:
  contents: write

jobs:
  sukuttyo_bbs_chat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Prepare README
        run: |
          # READMEが存在しない場合は作成
          if [ ! -f README.md ]; then
            echo "# SUKUTTYO@BBS チャットログ" > README.md
          fi

      - name: Write Message to README
        env:
          USERNAME: ${{ github.event.inputs.username }}
          MESSAGE: ${{ github.event.inputs.message }}
        run: |
          # メッセージが空の場合はデフォルトメッセージを使用
          MESSAGE="${MESSAGE:-デフォルトメッセージ}"
          
          # タイムスタンプ付きでメッセージを追記
          echo "" >> README.md
          echo "## $(date '+%Y-%m-%d %H:%M:%S')" >> README.md
          echo "\`$USERNAME\`: $MESSAGE" >> README.md

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Add new SUKUTTYO BBS message" || echo "No changes to commit"
          git push
